[package]
name = "wgsl-parse"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Parse a wgsl source file to a syntax tree"
repository.workspace = true
license.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
annotate-snippets = { version = "0.12.16", default-features = false }
derive_more = {
  version = "2.1.1",
  default-features = false,
  features = [
    "as_ref",
    "deref",
    "deref_mut",
    "from",
    "is_variant",
    "unwrap",
  ]
}
itertools = "0.15.0"
lalrpop-util = { version = "0.23.1", default-features = false }
lexical-parse-float = {
  version = "1.0.6",
  default-features = false,
  features = ["format", "power-of-two", "std"],
}
lexical-parse-integer = {
  version = "1.0.6",
  default-features = false,
  features = ["format", "power-of-two", "std"],
}
logos = { version = "0.16.1", default-features = false, features = ["export_derive"] }
pretty = { version = "0.12.5", default-features = false }
serde = { version = "1.0.229", default-features = false, features = ["derive", "rc", "std"], optional = true }
thiserror = { version = "2.0.21", default-features = false }
tokrepr = { workspace = true, optional = true }
wgsl-types = { workspace = true }

[features]
# experimental
generics = []
# See crates/wesl/Cargo.toml
naga-ext = ["wgsl-types/naga-ext"]
serde = ["dep:serde", "wgsl-types/serde"]
tokrepr = ["dep:tokrepr", "wgsl-types/tokrepr"]

[lints]
workspace = true
